### ISSUE TITLE
A way to get the return code from an sh* function interop call

### ISSUE THREAD

**Issue by chr15m** [chr15m/flk#12]
`(sh! 'ping ["goober.com"])` should result in `(error-code stdout-result stderr-result)`.

**Comment by chr15m** [comment]
This will probably require a bash level replacement for `sh*` in `extras.sh` because the existing implementation wraps the call in such a way that it's impossible to get at the return code.

**Comment by rosineygp** [comment]
Hi @chr15m 

The following function helps me to get exit code, for stderr I guess that needs to create a tmp file... :disappointed: 

but it, helps me a lot.

```clojure
(defn sh! [command]
  (let [cmd (str command "; echo «$?")
        result (str-split (str-replace (sh* cmd) "\n" "¶") "«")]
        (hash-map :out (str-replace (get result 0) "¶" "\n") :exit (get result 1))))

(def ls (sh! "ls -la"))
(println (get ls :out))
(println (get ls :exit))

(def err (sh! "laaaaa"))
(println (get err :out))
(println (get err :exit))
```

Thanks!

**Comment by rosineygp** [comment]
Ugly as f**k but works

``` clojure

(defn sh! [command]
  (let [uuid (str "/tmp/" (sh* "uuidgen"))
        cmd (str command " 2> " uuid "; echo «$?")
        result (str-split (str-replace (sh* cmd) "\n" "¶") "«")
        err (sh* (str "cat " uuid))]
    (sh* (str "rm " uuid))
    (hash-map :out (str-replace (get result 0) "¶" "\n") 
              :err err 
              :exit (read-string (get result 1)))))

(println (sh! 'ping ["goober.com"]))

(def ls (sh! "ls -la"))
(println (get ls :out))
(println (get ls :err))
(println (get ls :exit))

(def err (sh! "laaaaa"))
(println (get err :out))
(println (get err :err))
(println (get err :exit))
```

I guess `uuidgen` is default at ubuntu, a generic uuid can be used for safe files
https://github.com/dylanaraps/pure-bash-bible#generate-a-uuid-v4

escapes chars like ¶ and « should be changed to something better.

**Comment by chr15m** [comment]
What I was thinking of is using the `catch` function found here:

https://stackoverflow.com/questions/11027679/capture-stdout-and-stderr-into-different-variables/41069638#41069638

Just inlining that function into flk's bash functions and then writing a small wrapper to use it.

**Comment by chr15m** [comment]
This technique seems to work better:

https://stackoverflow.com/questions/11027679/capture-stdout-and-stderr-into-different-variables/18086548#18086548

PR coming through.

**Comment by chr15m** [comment]
Fixed on branch issue-12-sh-interop. @rosineygp please let me know if this solves your issue.

**Comment by rosineygp** [comment]
> Fixed on branch issue-12-sh-interop. @rosineygp please let me know if this solves your issue.

Works!!! :wink: 

I just expected the return as hash-map... like clojure https://clojuredocs.org/clojure.java.shell/sh, but it's not a real problem.

The bash solution is ugliest of my code... but works better :smiley: stderr and stout without create a tmp file is amazing.

Thanks @chr15m 

I will try to implement last reverse and other small clojure functions if it works fine all will make a PR.

**Comment by chr15m** [comment]
Oh, that hash-map thing would be great. :+1: Thanks for testing!
