### ISSUE TITLE
How do I get CLI args?

### ISSUE THREAD

**Issue by ivopt** [chr15m/flk#14]
Hi!

I have and maintain a number of bash scripts to do multiple tasks around a dev infrastructure.
I was quite excited when I saw fleck because it gave me hope to finally use a decent language and still benefit from not needing to install anything specific to run my scripts on a target machine.

Now.. My scripts need CLI arguments, like `deploy -on target_machine some_project`. But I can't seem to understand how a fleck script would get those CLI args...

Imagining the contrived example of a `sillyecho` script, what I was looking for was something like:

```
#!/usr/bin/env flk

(map (fn [l] (println l)) ARGV)
```

Where `ARGV` would be some construct that would give me the arguments from the CLI.

This would be invoked like: `sillyecho One Two Three`
And would output:

```
One
Two
Three
```

---

Is this possible?
If not, could this be added in?

Thanks!

**Comment by chr15m** [comment]
Hey @LynxEyes I forgot that the underlying `mal` implementation makes this available as a global list called `*ARGV*`. So your example above becomes:

```
#!/usr/bin/env flk

(map (fn [l] (println l)) *ARGV*)
```

Have updated the documentation, thanks for flagging this.
