### ISSUE TITLE
Add Shebang support for scripts?

### ISSUE THREAD

**Issue by charlespwd** [chr15m/flk#2]
:wave:

Tried the following and couldn't get it to run:

```
#!/usr/bin/env flk
(println "hello world")
```

```
$ ./test.clj
$
```

Currently looking into what we should do to make this work :thinking:

**Comment by charlespwd** [comment]
Ah it looks like that's not possible because of shebang nesting. 

> Most operating systems do not allow a shell script to be the interpreter in a shebang for security reasons. – [chepner Nov 14 '15 at 15:33](https://stackoverflow.com/q/33709635/2386851)

**Comment by chr15m** [comment]
Ah that's a bummer. What about if there was a small compiler script which would take your script + the fleck source and compile them together into a new file? Shouldn't be hard to whip up.

**Comment by chr15m** [comment]
I just whipped this up:

```
$ cat wow.clj 
(println "WOW")

$ make DEST=wow INSERT=./wow.clj
cat mal/bash/mal | sed '/then exit/,$d' > wow
cat src/extras.sh >> wow
echo 'read -d "" _REPCAPTURE <<INLINEMALFILE' >> wow
cat mal/lib/alias-hacks.mal  mal/lib/pprint.mal  >> wow
[ "./wow.clj" = "" ] || cat ./wow.clj >> wow
echo 'INLINEMALFILE\nREP "(do ${_REPCAPTURE})";\n' >> wow
cat src/file-repl.sh >> wow
chmod 755 wow

$ ./wow 
WOW
Fleck
user>
```

Would that work for you as a temporary solution?

**Comment by chr15m** [comment]
Docs here: https://github.com/chr15m/flk#compile

**Comment by chr15m** [comment]
@charlespwd since the fix for #3 I now see the following when I do this:

```
$ ./shebangtest
Error: "'#!/usr/bin/env' not found"
```

So maybe this is what was happening to you above but the error was getting swallowed?

This error is flk itself getting confused by the shebang and is something we could/should fix.

There seems to be some inconsistency with regards to nested shebangs - can I ask what OS you are on?

**Comment by charlespwd** [comment]
Sure, I'm on arch linux 5.3.13-arch1-1.

Would we have a `#!/usr/bin/env` in the middle of the file if we merge them like you said eariler? Especially since lisp/clojure doesn't use `#` as a comment.

Could simply write the script without the leading shebang though :thinking:.

**Comment by chr15m** [comment]
That `#!/usr/bin/env` already happens because of the way mal compiles the scripts together but it's not a problem. I think the fix for this is to get fleck to special-case parsing the first line of the file if it's a shebang and ignore it. Will investigate further.

**Comment by chr15m** [comment]
@charlespwd I just pushed a fix for using `flk` in the hash-bang. To test this:

 * Have `flk` on your path.
 * Have a script with `#!/usr/bin/env flk` as the first line.
 * Make it executable.

Then call your Fleck script and it should execute correctly.

Please let me know if you get a chance to test it so we can close this one.

**Comment by charlespwd** [comment]
Works! Awesome!

**Comment by chr15m** [comment]
@charlespwd thank you very much for testing.
