### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by klardotsh** [chr15m/flk#27]
I see upstream `mal` is MPL-2.0 (at that, the GPL-incompatible flavor thereof), but given that MPL is file-level copyleft, I can't use that to make assumptions about `flk`'s license. If you could throw a `LICENSE` or `COPYING` file in the tree and tag a new version, that would be awesome (otherwise, it's not safe to use, or to package in Linux distros, Brew, etc.)

**Comment by chr15m** [comment]
@klardotsh it seems safest to license `flk` under the same license as `mal`. Would that work for your purposes?

**Comment by klardotsh** [comment]
I don't feel it's my place to weigh in too heavily on your choice of license - if you think MPL-2.0 with the no-GPL-compat clause is safest, then go for it.

My only remaining question at that point is what the best way to handle packaging something written against `flk` is - since MPL is file-level, would that require applications written against `flk` to be MPL-2.0 as well if they use the bundler? (obviously this can be worked around by shipping `flk` and the application in separate files, so it's not the end of the world either way)

Thanks for the quick reply!

**Comment by chr15m** [comment]
@klardotsh that's a very good point. Something like BSD or MIT would seem to be much safer from that point of view. However, I don't even know if I can re-license `flk` since it includes portions of `mal`. I guess I am going to have to spend time researching the MPL. :thinking:

**Comment by chr15m** [comment]
> would that require applications written against flk to be MPL-2.0 as well if they use the bundler?

Seems like MPL-2.0 explicitly allows re-licensing:

> MPL software can thus be converted into a copyleft license such as the GPL or to a proprietary license (example: KaiOS). 
> -- Wikipedia

**Comment by klardotsh** [comment]
I dug a bit further into this. It looks like [mal upstream ships the full text of MPL-2.0](https://github.com/kanaka/mal/blob/0198b7a230e48a6e06fed419c406833904244941/LICENSE) but does not indicate that they're triggering Exhibit B (Incompatibility With Secondary Licenses, which then triggers Section 3.3's restrictions on distribution in a larger work), so it sounds like MPL-2.0 without Exhibit B here would make the "concatenated bundles via `flk`" distribution fine (disclaimer: I'm not a lawyer).

If @kanaka can confirm the Exhibit B thing that'd be awesome, but otherwise I think this is a good path to making this usable! Thanks for taking the time @chr15m!

**Comment by chr15m** [comment]
@klardotsh thanks for reasearching this. I have added MPL-2.0 license to the source.
