### ISSUE TITLE
doc should say flk requires bash 4 or greater

### ISSUE THREAD

**Issue by haroldcarr** [chr15m/flk#30]
because of the use of `declare -A`

[https://wiki-dev.bash-hackers.org/bash4](https://wiki-dev.bash-hackers.org/bash4)

**Comment by chr15m** [comment]
Hello! The README says this in the "why" section.

**Comment by haroldcarr** [comment]
Missed that.  Apologies.
Thanks for `flk` --- I haven't really used it yet, but I plan to.
