### ISSUE TITLE
Makefile compilation mode failing [needs more info]

### ISSUE THREAD

**Issue by Shinoa-Fores** [chr15m/flk#6]
When attempting to compile a script using the Makefile example in README: 
`make DEST=wow INSERT=./wow.clj NOREPL=1` I get the following error:
"./flk: line 1510: warning: here-document at line 1431 delimited by end-of-file (wanted `INLINEMALFILE')"

I am using GNU bash, version 4.4.23(1)-release (x86_64-pc-linux-gnu)

I will keep plugging away at it to see if I can find a cause, but perhaps a reader can shed light on this for me.

**Comment by chr15m** [comment]
Are you able to share the contents of `wow.clj`?

**Comment by Shinoa-Fores** [comment]
>Are you able to share the contents of wow.clj?

I just used the simple example from README too, put it in file called "wow.clj"
`(println "Hello world!") (println "Hostname:" (sh* "hostname")))`

**Comment by chr15m** [comment]
Very strange. I note there is a typo in what you have pasted - an extra brace at the end.

However, I think that's not what is causing this error. In fact it should not be possible for the error to occur as you've pasted it. You're saying that the invocation of `make` threw an error like `./flk: line 1510: warning:` however the Makefile does not ever call flk directly so I don't see how that error has arisen.

In order to replicate this can you please paste the exact sequence of what you ran and the contents of the relevant files.

**Comment by Shinoa-Fores** [comment]
Meh, I'll just close. I tried compiling any of the examples and get the same thing. No clue.

**Comment by chr15m** [comment]
@Shinoa-Fores can you tell me the exact output of the following commands when run inside the Fleck checkout?

 * `git status -s`
 * `git rev-parse HEAD`
 * `make DEST=hello INSERT=examples/hello.clj NOREPL=1`
 * `./hello`

My output for these commands is as follows:

```
$ git status -s
[no output]

$ git rev-parse HEAD
3ca21987b456eac18f9eeb4d3e9cc57761508028

$ make DEST=hello INSERT=examples/hello.clj NOREPL=1
cat mal/bash/mal | sed '/then exit/,$d' > hello
cat src/extras.sh >> hello
echo 'read -d "" _REPCAPTURE <<INLINEMALFILE' >> hello
cat mal/lib/alias-hacks.mal  mal/lib/trivial.mal  src/math.clj  src/reducers.clj  >> hello
[ "examples/hello.clj" = "" ] || cat examples/hello.clj >> hello
echo 'INLINEMALFILE\nREP "(do ${_REPCAPTURE})";\n' >> hello
if [ "1" = "" ]; then cat src/file-repl.sh; fi >> hello
chmod 755 hello

$ ./hello
Hello world!
This is diziet
Uptime is 06:14:44 up 20 days, 22:09,  4 users,  load average: 0.26, 0.36, 0.51
```

**Comment by chr15m** [comment]
@Shinoa-Fores oh, I think I have figured out what is going on.

Can you run `git submodule init; git submodule update` and then try again?

**Comment by chr15m** [comment]
If this is what is failing I'll add a note to the docs.

**Comment by Shinoa-Fores** [comment]
My output for the above commands:

```
$ git submodule init; git submodule update
Submodule 'mal' (https://github.com/chr15m/mal.git) registered for path 'mal'
Cloning into '/home/shinohai/devel/lisp/flk/mal'...
Submodule path 'mal': checked out '45eb7ae0c2d7359dce95da06b14df211179c75ee'

$ git status -s
[no output]

$ git rev-parse HEAD
3ca21987b456eac18f9eeb4d3e9cc57761508028

$ make DEST=hello INSERT=examples/hello.clj NOREPL=1
cd mal/bash && make mal
make[1]: Entering directory '/home/shinohai/devel/lisp/flk/mal/bash'
cat types.sh reader.sh printer.sh env.sh core.sh stepA_mal.sh | grep -v "^source " > mal.sh
echo "#!/usr/bin/env bash" > mal
cat mal.sh >> mal
chmod +x mal
make[1]: Leaving directory '/home/shinohai/devel/lisp/flk/mal/bash'
cat mal/bash/mal | sed '/then exit/,$d' > hello
cat src/extras.sh >> hello
echo 'read -d "" _REPCAPTURE <<INLINEMALFILE' >> hello
cat mal/lib/alias-hacks.mal  mal/lib/trivial.mal  src/math.clj  src/reducers.clj  >> hello
[ "examples/hello.clj" = "" ] || cat examples/hello.clj >> hello
echo 'INLINEMALFILE\nREP "(do ${_REPCAPTURE})";\n' >> hello
if [ "1" = "" ]; then cat src/file-repl.sh; fi >> hello
chmod 755 hello
$ ./hello 
./hello: line 1531: warning: here-document at line 1470 delimited by end-of-file (wanted `INLINEMALFILE')
```

So appears I'm still getting same error :/

Other info:

```
$ bash --version
GNU bash, version 4.4.23(1)-release (x86_64-pc-linux-gnu)

$gcc -v
gcc version 9.2.0 (Gentoo Hardened 9.2.0-r1 p2)
```

**Comment by Shinoa-Fores** [comment]
Just to check, also switched my compiler to gcc-7.3.0 but experience the same result.

**Comment by chr15m** [comment]
Fleck does not use the `gcc` compiler so that shouldn't be an issue.

This is a very interesting puzzle. Can you send me the last 10 lines of the `hello` script that is produced?

**Comment by chr15m** [comment]
Or if you have time to email me the whole thing, even better.

**Comment by chr15m** [comment]
It seems this error is related to Bash being sensitive to any characters before and after the here-document terminator.

 * https://stackoverflow.com/questions/27201004/line-54-warning-here-document-at-line-42-delimited-by-end-of-file-wanted-eof
 * https://www.krenger.ch/blog/bash-here-document-at-line-n-delimited-by-end-of-file-wanted-eof/
 * https://stackoverflow.com/questions/12503581/bash-warning-here-document-at-line-delimited-by-end-of-file-wanted-eof

We'll get to the bottom of this.

**Comment by chr15m** [comment]
@Shinoa-Fores tested and reported this as fixed! :tada:

Solution was here: https://stackoverflow.com/questions/8467424/echo-newline-in-bash-prints-literal-n
