### ISSUE TITLE
Which versions of bash does this support?

### ISSUE THREAD

**Issue by neuronsong** [chr15m/flk#8]
I'm running OSX catalina... and getting the following errors:
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
$ ./flk
./flk: line 9: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
./flk: line 1089: syntax error near unexpected token `<'
./flk: line 1089: `    [<]=num_lt'
./flk: line 1090: =]=num_lte: No such file or directory
./flk: line 1091: [: missing `]'
./flk: line 1092: [: missing `]'
./flk: line 1093: [+]=num_plus: command not found
./flk: line 1094: [-]=num_minus: command not found
./flk: line 1095: [__STAR__]=num_multiply: command not found
./flk: line 1096: [/]=num_divide: No such file or directory
./flk: line 1097: [time-ms]=time_ms: command not found
./flk: line 1099: [list]=_list: command not found
./flk: line 1100: [list?]=list?: command not found
./flk: line 1101: [vector]=_vector: command not found
./flk: line 1102: [vector?]=vector?: command not found
./flk: line 1103: [hash-map]=_hash_map: command not found
./flk: line 1104: [map?]=hash_map?: command not found
./flk: line 1105: [assoc]=assoc: command not found
./flk: line 1106: [dissoc]=dissoc: command not found
./flk: line 1107: [get]=get: command not found
./flk: line 1108: [contains?]=contains?: command not found
./flk: line 1109: [keys]=keys: command not found
./flk: line 1110: [vals]=vals: command not found
./flk: line 1112: [sequential?]=sequential?: command not found
./flk: line 1113: [cons]=cons: command not found
./flk: line 1114: [concat]=concat: command not found
./flk: line 1115: [nth]=nth: command not found
./flk: line 1116: [first]=_first: command not found
./flk: line 1117: [rest]=_rest: command not found
./flk: line 1118: [empty?]=empty?: command not found
./flk: line 1119: [count]=count: command not found
./flk: line 1120: [apply]=apply: command not found
./flk: line 1121: [map]=map: command not found
./flk: line 1123: [conj]=conj: command not found
./flk: line 1124: [seq]=seq: command not found
./flk: line 1126: [with-meta]=with_meta: command not found
./flk: line 1127: [meta]=meta: command not found
./flk: line 1128: [atom]=_atom: command not found
./flk: line 1129: [atom?]=atom?: command not found
./flk: line 1130: [deref]=deref: command not found
./flk: line 1131: [reset!]=reset_BANG: command not found
./flk: line 1132: syntax error near unexpected token `)'
./flk: line 1132: `    [swap!]=swap_BANG)'

**Comment by neuronsong** [comment]
I'm guessing this only works with at least bash 4.

**Comment by neuronsong** [comment]
Easy fix if you use homebrew.
Modify the shebang line in flk to "#!/usr/local/bin/bash" instead of "#!/usr/bin/env bash"
Then install bash 5 via homebrew.
$ brew install bash
$/usr/local/bin/bash --version
GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin19.0.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ ./flk
Fleck
user> (+ 1 2 3)
3
user> (+ 1 2 3 4 5)
3
user> (+ 3 2 1)
5
user>

**Comment by chr15m** [comment]
Thank you, I will add this information to the README.
